name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: php:8.4
      env:
        APP_ENV: testing
        DB_CONNECTION: mysql
        DB_HOST: mysql
        DB_PORT: 3306
        DB_DATABASE: laravel
        DB_USERNAME: root
        DB_PASSWORD: secret
        SESSION_DRIVER: array
        CACHE_STORE: array


    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: laravel
        ports:
          - 33066:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MySQL PDO Extension
        run: |
          apt-get update
          apt-get install -y libzip-dev unzip libpng-dev libonig-dev libxml2-dev
          docker-php-ext-install pdo pdo_mysql

      - name: Setup Composer
        run: |
          apt-get update && apt-get install -y unzip curl git libzip-dev libpng-dev libonig-dev libxml2-dev
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer

      - name: Install Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
          apt-get install -y nodejs

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Publish Ziggy Configuration
        run: php artisan ziggy:generate

      - name: Build Assets
        run: npm run build

      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL..."
          sleep 15

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Seed Database
        run: php artisan db:seed --force

      - name: Tests
        run: ./vendor/bin/pest

